### ISSUE TITLE
CORS errors loading fonts

### ISSUE THREAD

**Issue by daisylb** [djangocon/2018.djangocon.com.au#1]
On the live website, I get these three errors in the console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://fast.fonts.net/dv2/3/a32c3a17-3242-461c-a048-ca8e775582b1.woff?d44f19a684109620e484147eaf90e8185edd66a41b648a2a8173514ad5354e0fea1a46d920b8f5005fc774cc85e87c70bc5854d381bff33a0cfea5daaefe093455fc5b4d2f05ee52ea0b7da7919e&projectId=c70387ce-91f2-4965-9021-ab70eec030fa. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://fast.fonts.net/dv2/3/a21a792c-051c-4059-8719-ecc8749c99a6.woff?d44f19a684109620e484147eaf90e8185edd66a41b648a2a8173514ad5354e0fea1a46d920b8f5005fc774cc85e87c70bc5854d381bff33a0cfea5daaefe093455fc5b4d2f05ee52ea0b7da7919e&projectId=c70387ce-91f2-4965-9021-ab70eec030fa. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://fast.fonts.net/dv2/3/b0eddbbb-9e8e-4e08-bde1-965bb945f73a.woff?d44f19a684109620e484147eaf90e8185edd66a41b648a2a8173514ad5354e0fea1a46d920b8f5005fc774cc85e87c70bc5854d381bff33a0cfea5daaefe093455fc5b4d2f05ee52ea0b7da7919e&projectId=c70387ce-91f2-4965-9021-ab70eec030fa. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Perhaps the font hosting provider isn't configured for the `2018.` URL? Is that something under your control, @freakboy3742, or is it the agency that designed the site?

**Comment by freakboy3742** [comment]
Dang. I didn't pull updates from 2017 before committing the 2018 repo. Should be fixed now.
